### PR TITLE
Implementation of Specification pattern.

### PR DESCRIPTION
**Pull request by martinezdelariva**
Specification pattern by M.Fowler and E.Evans.

Includes:
- Single Specification.
- Composite Specification.

Not includes:
- Subsumption.
- Partially Satisfied Specification.

### CODE REVIEW

**Comment by monteiro** [comment]
+1

**Comment by carlosbuenosvinos** [comment]
I'll take a look today. Sorry for the delay.

**Comment by martinezdelariva** [comment]
@carlosbuenosvinos Friendly reminder. Any improvement, please let me know.
Thanks!.

**Comment by carlosbuenosvinos** [comment]
Done! I'll tag the new version.

**Comment by carlosbuenosvinos** [comment]
Done, 1.5.0

**Comment by martinezdelariva** [comment]
:+1:

**Pull request merged**
